[package]
name = "vault_program"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.9.1"
solana-program = "1.9.5"
spl-token = "3.3.0"
thiserror = "1.0.30"
